---
- hosts: '{{ remote_hosts }}'
  become: yes
  tasks:

  - name: Creating user for ubuntu hosts
    user: 
      name: '{{ ubuntu_insert_user }}' 
      force: yes

  - name: Placing key
    authorized_key: '{{ auth_key }}'

  - lineinfile: '{{ ubuntu_insert_user }}' 

- hosts: '{{ remote_freenas }}'
  become: yes
  tasks:
  - name: Creating user for FreeNAS hosts
    user: 
      name: '{{ freebsd_insert_user }}' 
      force: yes

  - name: Placing key
    authorized_key: '{{ auth_key }}'

  - lineinfile: '{{ freebsd_insert_user }}' 

