---
- hosts: '{{ remote_hosts }}'
  become: yes
  tasks:

  - name: Creating user for ubuntu hosts
    user: 
      name: '{{ insert_username }}' 
      comment: Ansible Management
      group: sudo
      force: yes

  - name: Placing key
    authorized_key: 
      user: '{{ insert_username }}' 
      key: '{{ auth_key }}'

  - lineinfile: 
      dest: '{{ ubuntu_line_dest }}'
      state: present
      regexp: '{{ line_regexp }}'
      line: '{{ insert_line }}'
  

- hosts: '{{ remote_freenas }}'
  become: yes
  tasks:
  - name: Creating user for FreeNAS hosts
    user: 
      name: '{{ insert_username }}' 
      comment: Ansible Management
      group: wheel
      force: yes

  - name: Placing key
    authorized_key: 
      user: '{{ insert_username }}' 
      key: '{{ auth_key }}'

  - lineinfile: 
      dest: '{{ freenas_line_dest }}'
      state: present
      regexp: '{{ line_regexp }}'
      line: '{{ insert_line }}'

