---
# Task 1: Fetch certificates from letsencrypt generation host
- hosts: '{{ letsencrypt_host }}'
  become: yes
  
  tasks:
        - name: Creates local directory to hold certificates
          file: 
            dest='{{ fetch_to_dir }}'
            state=directory 
            owner=root 
            group=root 
            mode=0644
        - acl: 
            name=/etc/letsencrypt/live 
            entity=ansible 
            etype=user 
            permissions="rwx" 
            state=present
            recursive=yes
        - name: Fetch live certificates folder from letsencrypt generation host to local
          synchronize:  
            src={{ item }} 
            dest='{{ fetch_to_dir }}' 
            mode=pull 
            recursive=yes 
            archive=no
            rsync_path="sudo rsync"
          with_items:
                - '{{ fetch_from_dir }}'

# Task 2: Copy certificates from local to remote hosts
- hosts: '{{ remote_hosts }}'
  become: yes

  tasks:
   - name: Creates destination directory on remote hosts
     file:
       path='{{ fetch_to_dir }}'
       state=directory

   - name: Send live certificates folder from local to remote hosts
     synchronize:  
     src={{ item }} 
     dest='{{ fetch_to_dir }}' 
     mode=push 
     recursive=yes 
     archive=no
     rsync_path="sudo rsync"
     with_items:
      - '{{ fetch_from_dir }}'

# Task 3: Copy certificates to proxmox directory
- hosts: '{{ proxmox_hosts }}'
  become: yes

  tasks:
  - name: Move and rename privkey to proxmox directory
    command:
       cp '{{ privkey_path }}' '{{ proxmox_privkey_path }}'

  - name: Move and rename fullchain to proxmox directory
    command:
       cp '{{ fullchain_path }}' '{{ proxmox_fullchain_path }}'

# Task 4: Copy certificates from local to FreeNAS host. Require separate task due to different root group. 
- hosts: '{{ freenas_hosts }}'
  become: yes

  tasks:
   - name: Creates destination directory on FreeNAS
     file:
       path='{{ fetch_to_dir }}'
       state=directory

   - name: Send live certificates folder from local to remote hosts
     synchronize:  
     src={{ item }} 
     dest='{{ fetch_to_dir }}' 
     mode=push 
     recursive=yes 
     archive=no
     rsync_path="sudo rsync"
     with_items:
      - '{{ fetch_from_dir }}'
  
   - name: Move privkey to FreeNAS certificates directory
     command:
        cp '{{ privkey_path }}' '{{ freenas_privkey_path }}'

   - name: Move fullchain to FreeNAS certificates directory
     command:
        cp '{{ fullchain_path }}' '{{ freenas_fullchain_path }}'

# Task 5: Modify permissions and copy certificates to SABnzbd folder
- hosts: '{{ downloadstation_hosts }}'
  become: yes

  tasks:
   - name: Modify ownership of privkey
     file:
        path: '{{ privkey_path }}'
        owner: '{{ process_owner }}'
        group: '{{ process_owner }}'
   - name: Modify ownership of cert
     file:
        path: '{{ cert_path }}'
        owner: '{{ process_owner }}'
        group: '{{ process_owner }}'

   - name: Move and rename privkey to SABnzbd directory
     command:
        cp '{{ privkey_path }}' '{{ sabnzbd_privkey_path }}'
   - name: Move and rename cert to SABnzbd directory
     command:
        cp '{{ cert_path }}' '{{ sabnzbd_cert_path }}'


# Task 6: Create PKCS12 archive of the certificate and key for Plex
- hosts: '{{ plex_hosts }}'
  become: yes
  tasks:
  - name: Create PKCS12 archive of the certificate and key 
    command:
       openssl pkcs12 -export -in '{{ fullchain_path }}' -inkey '{{ privkey_path }}' -out '{{ plex_pkcs_path }}' -name "cert" -passout '{{ plex_pkcs_pass }}'
  - name: Modify ownership of PKCS12 archive
    file:
       path: '{{ plex_pkcs_path }}'
       owner: '{{ process_owner }}'
       group: '{{ process_owner }}'


# Task 7: Copy certificates to PRTG directory 
- hosts: '{{ prtg_hosts }}'
  tasks:
   - name: Copy privkey to PRTG folder
     win_copy:
        src: '{{ privkey_path }}'
        dest: '{{ prtg_privkey_path }}'
   - name: Copy cert to PRTG folder
     win_copy:
        src: '{{ cert_path }}'
        dest: '{{ prtg_cert_path }}'

# Task 8: Copy certificates to Ansible Tower directory 
- hosts: localhost
  tasks:
   - name: Copy privkey to Ansible Tower folder
     copy:
        src: '{{ privkey_path }}'
        dest: '{{ ansible_privkey_path }}'
   - name: Copy cert to Ansible Tower folder
     copy:
        src: '{{ cert_path }}'
        dest: '{{ ansible_cert_path }}'


