---
#Task 1: Fetch certificates from letsencrypt generation host
- hosts: '{{ letsencrypt_host }}'
  become: yes
  
  tasks:
        - name: Creates local directory to hold certificates
          file: 
            dest='{{ fetch_to_dir }}'
            state=directory 
            owner=root 
            group=root 
            mode=0644

        - name: Fetch live certificates folder from letsencrypt generation host to local
          synchronize:  
            src={{ item }} 
            dest='{{ fetch_to_dir }}' 
            mode=pull 
            recursive=yes 
            rsync_path="sudo rsync"
          with_items:
                - '{{ fetch_from_dir }}'
                
#Task 2: Copy certificates from local to remote hosts
- hosts: '{{ remote_hosts }}'
  become: yes

  tasks:
   - name: Creates destination directory on remote hosts
     file:
       path=/etc/letsencrypt/live
       state=directory

   - name: Copy certificates directory from local to remote hosts
     copy:
       src:    '{{ item.src }}'
       dest:   '{{ item.dest }}'
       owner:  root
       group:  root
       mode:   '{{ item.mode }}'
       force:  yes
     with_items:
      - src: '{{ fetch_from_dir }}' 
        dest: '{{ fetch_to_dir }}' 
        mode: '0644'
#Task3: 
- hosts: '{{ proxmox_hosts }}'
  become: yes

  tasks:
  - name: Move and rename privkey.pem to proxmox directory
    command:
       cp '{{ original_privkey_path }}' '{{ proxmox_privkey_path }}'

  - name: Move and rename fullchain.pem to proxmox directory
    command:
       cp '{{ original_fullchain_path }}' '{{ proxmox_fullchain_path }}'
