---
# Task 1: Fetch certificates from letsencrypt generation host
- hosts: '{{ letsencrypt_host }}'
  become: yes
  
  tasks:
        - name: Creates local directory to hold certificates
          file: 
            dest='{{ fetch_to_dir }}'
            state=directory 
            owner=root 
            group=root 
            mode=0644

        - name: Fetch live certificates folder from letsencrypt generation host to local
          synchronize:  
            src={{ item }} 
            dest='{{ fetch_to_dir }}' 
            mode=pull 
            recursive=yes 
            rsync_path="sudo rsync"
          with_items:
                - '{{ fetch_from_dir }}'
                
# Task 2: Copy certificates from local to remote hosts
- hosts: '{{ remote_hosts }}'
  become: yes

  tasks:
   - name: Creates destination directory on remote hosts
     file:
       path=/etc/letsencrypt/live
       state=directory

   - name: Copy certificates directory from local to remote hosts
     copy:
       src:    '{{ item.src }}'
       dest:   '{{ item.dest }}'
       owner:  root
       group:  root
       mode:   '{{ item.mode }}'
       force:  yes
     with_items:
      - src: '{{ fetch_from_dir }}' 
        dest: '{{ fetch_to_dir }}' 
        mode: '0644'
        
# Task 3: Copy certificates to proxmox directory
- hosts: '{{ proxmox_hosts }}'
  become: yes

  tasks:
  - name: Move and rename privkey to proxmox directory
    command:
       cp '{{ privkey_path }}' '{{ proxmox_privkey_path }}'

  - name: Move and rename fullchain to proxmox directory
    command:
       cp '{{ fullchain_path }}' '{{ proxmox_fullchain_path }}'

# Task 4: Copy certificates from local to FreeNAS host. Require separate task due to different root group. 
- hosts: '{{ freenas_hosts }}'
  become: yes

  tasks:
   - name: Creates destination directory on FreeNAS
     file:
       path='{{ fetch_to_dir }}'
       state=directory

   - name: Copy fullchain and privkey.pem to remote hosts
     copy:
       src:    '{{ item.src }}'
       dest:   '{{ item.dest }}'
       owner:  root
       group:  wheel
       mode:   '{{ item.mode }}'
     with_items:
      - src: '{{ fetch_from_dir }}' 
        dest: '{{ fetch_to_dir }}' 
        mode: '0644'
  
   - name: Move and rename privkey to FreeNAS certificates directory
     command:
        mv '{{ privkey_path }}' '{{ freenas_privkey_path }}'

   - name: Move and rename fullchain to FreeNAS certificates directory
     command:
        mv '{{ fullchain_path }}' '{{ freenas_fullchain_path }}'

# Task 5: Modify permissions and copy certificates to SABnzbd folder
- hosts: downloadstation
  become: yes

  tasks:

   - name: Modify ownership of privkey.pem to sixthmarch
     file:
        path: '{{ privkey_path }}'
        owner: sixthmarch
        group: sixthmarch
   - name: Set ownership of cert.pem to sixthmarch
     file:
        path: '{{ cert_path }}'
        owner: sixthmarch
        group: sixthmarch

   - name: Move and rename privkey to SABnzbd directory
     command:
        cp '{{ privkey_path }}' '{{ sabnzbd_privkey_path }}'
   - name: Move and rename cert to SABnzbd directory
     command:
        cp '{{ cert_path }}' '{{ sabnzbd_cert_path }}'
