---
- hosts: '{{ hosts }}'
  become: yes
  tasks:
        - name: Creates destination directory
          file: 
            dest='{{ fetch_to_dir }}'
            state=directory 
            owner=root 
            group=root 
            mode=0644

        - name: Fetch stuff from the remote and save to local
          synchronize:  
            src={{ item }} 
            dest='{{ fetch_to_dir }}' 
            mode=pull 
            recursive=yes 
            rsync_path="sudo rsync"
          with_items:
                - '{{ fetch_from_dir }}'



